# -*- coding: utf-8 -*-
"""
Click commands.
"""
from __future__ import print_function

import asyncio
import os
from builtins import next, str
from datetime import datetime
from glob import glob
from subprocess import call, check_output

import click

from ultraqc.database import init_db

HERE = os.path.abspath(os.path.dirname(__file__))
PROJECT_ROOT = os.path.join(HERE, os.pardir)
TEST_PATH = os.path.join(PROJECT_ROOT, "tests")
ULTRAQC_DATE_FORMAT = "%Y-%m-%d, %H:%M"


@click.command()
def test():
    """
    Run the tests.
    """
    import pytest

    rv = pytest.main([TEST_PATH, "--verbose"])
    exit(rv)


@click.command()
@click.option(
    "-f",
    "--fix-imports",
    default=False,
    is_flag=True,
    help="Fix imports using isort, before linting",
)
def lint(fix_imports):
    """
    Lint and check code style.
    """
    all_py = check_output(["git", "ls-files", "*.py"]).decode().split("\n")

    def execute_tool(description, *args):
        """
        Execute a checking tool with its arguments.
        """
        command_line = list(args) + all_py
        click.echo("{}: {}".format(description, " ".join(command_line)))
        rv = call(command_line)
        if rv != 0:
            exit(rv)

    if fix_imports:
        execute_tool("Fixing import order", "isort", "-rc")
    execute_tool("Checking code style", "flake8")


@click.command()
def clean():
    """
    Remove *.pyc and *.pyo files recursively.
    """
    for dirpath, dirnames, filenames in os.walk("."):
        for filename in filenames:
            if filename.endswith(".pyc") or filename.endswith(".pyo"):
                full_pathname = os.path.join(dirpath, filename)
                click.echo("Removing {}".format(full_pathname))
                os.remove(full_pathname)


@click.command()
def routes():
    """
    Display all URL routes.
    """
    from ultraqc.app import create_app

    app = create_app()
    click.echo("Available routes:")
    click.echo("-" * 60)
    for route in app.routes:
        if hasattr(route, "path"):
            methods = getattr(route, "methods", ["GET"])
            click.echo(f"{', '.join(methods):20} {route.path}")


@click.command()
@click.option("--db-url", default=None, help="Database URL to initialize")
def initdb(db_url):
    """Initialize the database."""
    from ultraqc.settings import get_settings

    if db_url is None:
        settings = get_settings()
        db_url = settings.SQLALCHEMY_DATABASE_URI

    click.echo(f"Initializing database: {db_url}")
    asyncio.run(init_db(db_url))
    click.echo("Database initialized successfully!")


def ultraqc_date_type(arg):
    return datetime.strptime(arg, ULTRAQC_DATE_FORMAT)


@click.option(
    "--date",
    default=None,
    help="Custom date to be stored for all the MultiQC files provided. Should be provided in the date format {}".format(
        ULTRAQC_DATE_FORMAT
    ),
    type=ultraqc_date_type,
)
@click.command(context_settings=dict(help_option_names=["-h", "--help"]))
@click.argument(
    "json_files",
    type=click.Path(exists=True),
    nargs=-1,
    required=True,
    metavar="<multiqc_data.json>",
)
def upload(json_files, date):
    """
    Manually upload MultiQC JSON files to UltraQC.

    This function allows you to submit one or more MultiQC JSON data files to UltraQC.
    These files are generated by MultiQC v1.3 and above, and are typically found in
    `multiqc_data/multiqc_data.json`.

    Note that this functionality is designed to be run from a totally separate location
    to the main UltraQC installation. It imports and uses MultiQC code, so it should be
    run in the same environment where you usually use MultiQC.

    It should probably be part of MultiQC, but it's difficult to add separate subcommand
    functionality there.
    """

    try:
        from multiqc.utils import config as multiqc_config
        from multiqc.utils import log as multiqc_log
        from multiqc.utils import ultraqc as multiqc_ultraqc
    except ImportError:
        print("Error - This function requires MultiQC to be installed.")
    else:
        import gzip
        import json

        multiqc_log.init_log(multiqc_config.logger, loglevel="INFO")
        multiqc_config.mqc_load_userconfig()
        if not multiqc_config.ultraqc_url:
            print("Error - MultiQC ultraqc_url not set.")
        else:
            # Loop through supplied JSON files
            for fn in json_files:
                multiqc_config.logger.info("Uploading file '{}'".format(fn))
                if fn.endswith(".gz"):
                    with gzip.open(fn, "rb") as fh:
                        multiqc_json_dump = json.load(fh)
                else:
                    with open(fn, "r") as fh:
                        multiqc_json_dump = json.load(fh)

                # Patch in the date provided on the CLI
                if date is not None:
                    multiqc_json_dump["config_creation_date"] = date.strftime(
                        ULTRAQC_DATE_FORMAT
                    )
                multiqc_ultraqc.multiqc_api_post(multiqc_json_dump)
